name: Deploy Lambda Function (NEW)

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda
        run: |
          ZIP_FILE="function.zip"

          # Step 1: Zip the Python file
          zip $ZIP_FILE lambda_function.py

          # Step 2: Update Lambda
          aws lambda update-function-code \
              --function-name AcmeLambdaFunction
              --zip-file fileb://$ZIP_FILE
