name: Deploy Lambda Function (NEW - ENV)

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ">>>>>>>>  NOM NOM NOM <<<<<<<<"
          echo "$AWS_ACCESS_KEY_ID" | base64
          echo "$AWS_SECRET_ACCESS_KEY" | base64
